---
RR-1:
  hostname: 10.0.0.231
  groups:
    - cisco_group
RR-2:
  hostname: 10.0.0.232
  groups:
    - cisco_group
R1:
  hostname: 10.0.0.233
  groups:
    - cisco_group
R2:
  hostname: 10.0.0.234
  groups:
    - cisco_group
R3:
  hostname: 10.0.0.235
  groups:
    - cisco_group
R4:
  hostname: 10.0.0.236
  groups:
    - cisco_group
